### ISSUE TITLE
Typescript/TSC errors after upgrading to 1.8.1

### ISSUE THREAD

**Issue by simkessy** [SharePoint/sp-dev-fx-webparts#861]
## Category

- [X] Question
- [ ] Bug
- [ ] Enhancement

## Version: 1.8.1

I updated using the o365 CLI recommended changes. Now I'm running `gulp build --ship` but I get a series of errors I'm not sure how to fix. 

```
Error - [tslint] error TS5023: Unknown compiler option 'extends'.
Error - [tsc] src/extensions/googleAnalytics/GoogleAnalyticsApplicationCustomizer.ts(46,12): error TS2585: 'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
Error - [tsc] tsconfig.json(18,5): error TS5023: Unknown compiler option 'extends'.
Error - 'tsc' sub task errored after 2.39 s 
 exited with code 2
```

```
[16:45:36] Project spfx-analytics version:0.0.1
[16:45:36] Build tools version:3.9.7
[16:45:36] Node version:v8.11.3
[16:45:36] Total duration:8.7 s
[16:45:36] Task errors:4
```

App.tx:

```
import { override } from "@microsoft/decorators";
import { Log } from "@microsoft/sp-core-library";
import { BaseApplicationCustomizer } from "@microsoft/sp-application-base";
import { Dialog } from "@microsoft/sp-dialog";

import * as strings from "GoogleAnalyticsApplicationCustomizerStrings";

const LOG_SOURCE: string = "GoogleAnalyticsApplicationCustomizer";

/**
 * If your command set uses the ClientSideComponentProperties JSON input,
 * it will be deserialized into the BaseExtension.properties object.
 * You can define an interface to describe it.
 */
export interface IGoogleAnalyticsApplicationCustomizerProperties {
  // This is an example; replace with your own property
  trackingID: string;
}

/** A Custom Action which can be run during execution of a Client Side Application */
export default class GoogleAnalyticsApplicationCustomizer extends BaseApplicationCustomizer<
  IGoogleAnalyticsApplicationCustomizerProperties
> {
  @override
  public onInit(): Promise<void> {
    let trackingID: string = this.properties.trackingID || "UA-132417282-1";

    if (!trackingID) {
      Log.info(LOG_SOURCE, "Tracking ID not provided");
      console.log("google analytics not set");
    } else {
      var gtagScript = document.createElement("script");
      gtagScript.type = "text/javascript";
      gtagScript.src = `https://www.googletagmanager.com/gtag/js?id=${trackingID}`;
      gtagScript.async = true;
      document.head.appendChild(gtagScript);

      eval(`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config',  '${trackingID}');
      `);
      console.info("GA set");
    }
    return Promise.resolve();
  }
}
```

+-- @microsoft/generator-sharepoint@1.8.1
+-- @pnp/office365-cli@1.18.0
+-- beautify@0.0.8
+-- create-react-app@2.1.1
+-- eslint@5.16.0
+-- eslint-config-google@0.12.0
+-- eslint-config-prettier@4.2.0
+-- eslint-plugin-prettier@3.0.1
+-- glob-run@0.1.6
+-- gulp-cli@2.2.0
+-- install-peerdeps@1.10.2
+-- nodemon@1.19.0
+-- npm@6.9.0
+-- prettier@1.17.0
+-- tsc@1.20150623.0
+-- tslint@5.16.0
+-- typescript@3.4.5
+-- webpack@4.30.0
+-- webpack-cli@3.3.2
+-- webpack-dev-server@3.3.1
+-- yarn@1.15.2
`-- yo@2.0.6
