### ISSUE TITLE
react-test-renderer version for react 16.3.2

### ISSUE THREAD

**Issue by xyz92** [SharePoint/sp-dev-fx-webparts#699]
- [x] Question
- [ ] Bug
- [ ] Enhancement

What version of react-test-renderer is required with react 16.3.2? After updating react from 15.6.2 to 16.3.2 as a part of SPFx version upgrade to 1.7.0, my react tests are failing with error  Cannot find module 'react/lib/React' from 'ReactShallowRenderer.js'. Currently I am using "react-test-renderer": "15.5.4". Should I update the packages: 

 "@types/enzyme": "3.1.11",
 "@types/enzyme-adapter-react-15": "1.0.2",
"enzyme": "3.3.0",
 "enzyme-adapter-react-15": "1.7.0",

**Comment by VelinGeorgiev** [comment]
Do you refer to the react-jest-testing sample?

**Comment by xyz92** [comment]
@VelinGeorgiev Yes

**Comment by VelinGeorgiev** [comment]
I will try to upgrade the sample next week and let you know if i was able to reproduce it and fix it.

**Comment by xyz92** [comment]
Appreciate your help. Thank you! 

Could you please share the steps you followed to upgrade SPFx to 1.7.0? Thank you!

**Comment by VelinGeorgiev** [comment]
I am using the [Office 365 CLI](https://pnp.github.io/office365-cli/cmd/spfx/project/project-upgrade/) to do that. Here is a blog post on how to use it https://blog.mastykarz.nl/upgrade-sharepoint-framework-project-office-365-cli/. 

After you upgrade the solution, you will have to in addition manually upgrade the enzyme packages and tests imports to make them work with react 16.

**Comment by xyz92** [comment]
Thank you so much!

**Comment by xyz92** [comment]
@VelinGeorgiev What version of npm and node are you using for SPFx 1.7.0?
